# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9714f924fa5401f2f25a5ce354bc8dd16e51429c65f1bc35aa3b0e916933ff778484bcdb7daf6ba1959ae174951d9c1c38201e0d5fc2f20384c5f349e14ebc4

test:
  secret_key_base: 485695207a063cceef10646606edc9af44b11d51d073aab1eb1c5d2874fb0400dce70510ad35dcd8d057e50136cef7322849316012ba18fa5c17ea094bcd7a07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
